name: flutter_keychain
description: Flutter secure storage via Keychain and Keystore
version: 2.1.0
homepage: https://github.com/jeroentrappers/flutter_keychain

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: be.appmire.flutterkeychain
        pluginClass: FlutterKeychainPlugin
      ios:
        pluginClass: FlutterKeychainPlugin
